export const POKEDEX_FETCH_REQUEST = "POKEDEX_FETCH_REQUEST";
export const POKEDEX_FETCH_REQUEST_SUCCESS = "POKEDEX_FETCH_REQUEST_SUCCESS";
export const POKEDEX_FETCH_REQUEST_FAILURE = "POKEDEX_FETCH_REQUEST_FAILURE";

export const POKEDEX_SEARCH_FETCH_REQUEST = "POKEDEX_SEARCH_FETCH_REQUEST";
export const POKEDEX_SEARCH_FETCH_REQUEST_SUCCESS = "POKEDEX_SEARCH_FETCH_REQUEST_SUCCESS";
export const POKEDEX_SEARCH_FETCH_REQUEST_FAILURE = "POKEDEX_SEARCH_FETCH_REQUEST_FAILURE";

export const POKEDEX_DETAIL_FETCH_REQUEST = "POKEDEX_DETAIL_FETCH_REQUEST";
export const POKEDEX_DETAIL_FETCH_REQUEST_SUCCESS = "POKEDEX_DETAIL_FETCH_REQUEST_SUCCESS";
export const POKEDEX_DETAIL_FETCH_REQUEST_FAILURE = "POKEDEX_DETAIL_FETCH_REQUEST_FAILURE";

export const POKEDEX_ARRAY_STORE_REQUEST = "POKEDEX_ARRAY_STORE_REQUEST";

export const POKEDEX_CLEAN_REQUEST = "POKEDEX_CLEAN_REQUEST";

export const POKEDEX_DETAIL_CLEAN_REQUEST = "POKEDEX_DETAIL_CLEAN_REQUEST";

export const POKEDEX_SEARCH_CLEAN_REQUEST = "POKEDEX_SEARCH_CLEAN_REQUEST";
export const POKEDEX_ARRAY_CLEAN_REQUEST = "POKEDEX_ARRAY_CLEAN_REQUEST";
