export const POKEDEX_FETCH_REQUEST = "POKEDEX_FETCH_REQUEST";
export const POKEDEX_FETCH_REQUEST_SUCCESS = "POKEDEX_FETCH_REQUEST_SUCCESS";
export const POKEDEX_FETCH_REQUEST_FAILURE = "POKEDEX_FETCH_REQUEST_FAILURE";

export const POKEDEX_DETAIL_FETCH_REQUEST = "POKEDEX_DETAIL_FETCH_REQUEST";
export const POKEDEX_DETAIL_FETCH_REQUEST_SUCCESS = "POKEDEX_DETAIL_FETCH_REQUEST_SUCCESS";
export const POKEDEX_DETAIL_FETCH_REQUEST_FAILURE = "POKEDEX_DETAIL_FETCH_REQUEST_FAILURE";